name: Circuit Animation Based on Total Commits

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour to update the circuit animation

jobs:
  update-circuit:
    runs-on: ubuntu-latest

    steps:
      - name: Get all repositories
        id: repos
        run: |
          repos=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/Yami1106/repos?per_page=100" | jq -r '.[].name')
          echo "repos=$repos" >> $GITHUB_ENV

      - name: Calculate total commits
        id: commits
        run: |
          total_commits=0
          for repo in ${{ env.repos }}; do
            commits=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/Yami1106/$repo/stats/contributors" | jq '[.[].total | select(. != null)] | add')
            if [ -n "$commits" ]; then
              total_commits=$((total_commits + commits))
            fi
          done
          echo "Total commits: $total_commits"
          echo "total_commits=$total_commits" >> $GITHUB_ENV

      - name: Update SVG Animation Speed
        run: |
          speed=$(echo "scale=2; 5/(${{ env.total_commits }} + 1)" | bc -l) # Adjust speed based on commits
          sed -i "s/dur=\"[0-9.]*s\"/dur=\"${speed}s\"/" assets/animated-circuit.svg

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/animated-circuit.svg
          git commit -m "Updated circuit animation based on total commits"
          git push
